.devcontainer/docker-compose.yml
app/Dockerfile
app/Makefile
app/commands/sre.py
app/commands/utils.py
app/main.py
app/requirements_dev.txt
app/tests/commands/test_sre.py
app/tests/commands/test_utils.py
app/tests/test_main.py

This PR adds the `/sre` command to the bot. Currently only the `help` and `version` commands are supported.

feat: SRE command

---

.devcontainer/docker-compose.yml
.gitignore
app/commands/helpers/webhook_helper.py
app/commands/sre.py
app/main.py
app/models/webhooks.py
app/requirements.txt
app/tests/commands/helpers/test_webhook_helper.py
app/tests/commands/test_sre.py
app/tests/models/test_webhooks.py
terraform/dynamodb.tf
terraform/iam.tf

Closes #8. Is part of #7. This PR adds the following subcommand to the SRE Bot:
```
`/sre webhooks create` - create a new webhook
`/sre webhooks help` - show this help text
`/sre webhooks list` - lists webhooks
```
Which are part of the plan to route slack webhooks through the bot. Webhooks are created through the `create` command and have the following structure in DynamoDB
```
Item={
"id": {"S": id},
"channel": {"S": channel},
"name": {"S": name},
"created_at": {"S": str(datetime.datetime.now())},
"active": {"BOOL": True},
"user_id": {"S": user_id},
},
```
the `list` subcommand will present a simple interface to reveal or enable/disable webhook URLs. Every activity is also posted into the relevant channels as well as sent to the user in ephemeral messages, as well as logged out.

feat: webhooks storage in dynamodb

---

app/commands/helpers/incident_helper.py
app/commands/sre.py
app/integrations/google_drive.py
app/main.py
app/tests/commands/helpers/test_incident_helper.py
app/tests/commands/test_sre.py
app/tests/intergrations/test_google_drive.py

Closes #18. This PR adds a UI to manage metadata for folders in Google Drive. Metadata it app specific so it needs to be either managed through the slack UI or a web UI, but can't be done through the Google Drive UI, where one would think it would be.
Refactored folder list
Viewing metadata, no items
Adding metadata
Viewing metadata, one item

feat: adds metadata to folder

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml
app/commands/incident.py
app/integrations/google_drive.py
app/integrations/opsgenie.py
app/tests/commands/test_incident.py
app/tests/intergrations/test_google_drive.py
app/tests/intergrations/test_opsgenie.py
terraform/ecs.tf
terraform/secretsmanager.tf
terraform/templates/sre-bot.json.tpl
terraform/variables.tf

Closes #12. This PR adds code that will check for a `genie_schedule` on the folder metadata, pull out the emails of the people on-call for that schedule, look them up in slack, and add them to the incident channel. It also includes the names of the people on-call at the time in the incident document.

feat: opsgenie integration

---

app/commands/helpers/incident_helper.py
app/tests/commands/helpers/test_incident_helper.py

Refactors the modal code slightly to show a loading dialog before updating the modal. The reason is that the initial modal needs to respond within three seconds and sorting through all the stale incidents can last longer :(. You can see this behaviour in slack if you load their channel lists, although they have a much nicer loading animation.

refactor: Adds a loading screen for stale incidents

---

app/commands/helpers/incident_helper.py
app/jobs/notify_stale_incident_channels.py
app/jobs/scheduled_tasks.py
app/main.py
app/requirements.txt
app/tests/commands/helpers/test_incident_helper.py
app/tests/jobs/test_notify_stale_incident_channels.py
app/tests/jobs/test_scheduled_tasks.py
app/tests/test_main.py

Close #21. This PR adds a scheduler that will run a job every day at 17:00 GMT to see if any incident channels have been stale for more that 14 days. If it does it will send the following message:

feat: stale reminder

---

app/commands/helpers/incident_helper.py
app/commands/incident.py
app/integrations/google_drive.py
app/main.py
app/tests/commands/helpers/test_incident_helper.py
app/tests/intergrations/test_google_drive.py
app/tests/test_main.py

Part of #16. The PR introduce the `/sre incident roles` which provides a UI to manage incident roles inside an incident channel. If you are not in an incident channel, the bot will inform you:
If you are in an incident channel you will see the following:
Once you have chosen an OL and IC it will notify the channel:
and sets the topic:

feat: set roles in incident channel

---

app/Dockerfile
app/bin/entry.sh
app/tests/jobs/test_notify_stale_incident_channels.py
terraform/iam.tf
terraform/templates/sre-bot.json.tpl

This PR loads the ENV variables from the param store instead of the secret store.

feat: load env from paramstore on startup

---

app/commands/incident.py
app/tests/commands/test_incident.py

Currently can't acknowledge the slack message in the billing ops channel. Adding additional logging to get more details on why the slack api call is failing.
```
ERROR:slack_bolt.App:Failed to run listener function (error: The request to the Slack API failed. (url: https://www.slack.com/api/chat.update)
The server responded with: {'ok': False, 'error': 'invalid_blocks'})
```

feat: more logging to debug failed acknowledgement

---

app/commands/incident.py
app/tests/commands/test_incident.py

If the webhook being wrapped contains `rich_text` the call to slack will fail since rich_text blocks are only available for 1st party Slack clients (meaning Desktop, iOS, Android Slack apps)
`The server responded with: {'ok': False, 'error': 'invalid_blocks'})`
According to https://github.com/slackapi/bolt-js/issues/1324 we can drop the blocks element as long as the text parameter is valid. Tested via Postman and it's working as we expect with the AWS SNS topics.

fix: drop rich_text blocks since its not supported by API

---

app/commands/aws.py
app/integrations/aws_account_health.py
app/main.py
app/requirements.txt
app/tests/commands/test_aws.py
app/tests/intergrations/test_aws_account_health.py

This PR adds the `/aws health` command that should show you health data for specific account in AWS. You start by selecting an account from a drop down:
and then shows some health data on the account. Currently only the cost section is hooked up to show data from the last two months:
The security section is a placeholder and will be hooked up shortly.

feat: add account health check endpoint

---

app/tests/commands/test_atip.py

Fixed unit tests that were not actually testing due to an issue with `assert mock.function.called*`

fix: unit tests for i18n support

---

app/commands/incident.py
app/tests/commands/test_incident.py

Closes #95 where if a channel name was longer than 60 chars and less than 80 it would pass validation but not create the channel because we added an `incident-YYYY-MM-DD-` prefix which is 20 chars long and Slack channel names can only be 80 characters.

fix: Invalid name lengths

---

app/commands/atip.py
app/tests/commands/test_atip.py

Fixes an additional issue when starting the ATIP command with an argument such as
`atip start 1234`

fix: atip command with argument

---

.github/workflows/ossf-scorecard.yml

Closes https://github.com/cds-snc/site-reliability-engineering/issues/742. This PR adds a workflow that will use the OSSF Scorecard action on this repository and upload the result to Sentinel.

feat: Implement OSSF Scorecard

---

.github/workflows/build_and_deploy.yml
.github/workflows/docker_vulnerability_scan.yml

Update the Docker scans to look for the `linux/arm64` platform version of the Docker image.  This fixes the `image does not exist` error.

fix: set the Docker default platform to arm64

---

.github/workflows/build_and_deploy.yml

Latest release contains the fix for re-tagging a non `linux/amd64` architecture Docker image.
- cds-snc/security-tools#200

chore: bump to latest generate SBOM action

---

app/server/event_handlers/aws.py
app/tests/server/event_handlers/test_aws_handler.py

This PR adds a feature that handles Abuse notifications from our internal sre notification end points. Abuse notifications are filtered in event bridge, sent to the Internal SRE event topic, sent to the SRE Bot and the put into the channel.

feat: handle abuse notifications

---

app/integrations/sentinel.py
app/server/server.py
app/tests/server/test_server.py

Closes #178. Currently if there is an unrecognized AWS event, the content is posted as empty and we get an empty notification with the Acknowledge and Ignore buttons. What the fix does is if the message is empty, it should not post the message in Slack.
I also added timeouts (although quite large mostly to satisfy bandit) to the requests methods in order to satisfy bandit security scan.

Fix a bug where empty messages are being posted to Slack

---

app/commands/helpers/webhook_helper.py
app/main.py
app/tests/commands/helpers/test_webhook_helper.py

Closes #197 
There is a bug in the SRE bot due to a limitation in Slacks API, where you can't display more than 100 blocks in a modal (https://api.slack.com/reference/block-kit/blocks). This was not an issue before but as we create more webhooks, we are currently hitting the 100 block limit and will continue to do so. This PR contains a fix where we are displaying 3 webhooks at a time for usability reasons and are implementing a Next page that we can scroll to.

Fixing bug where block sizes of more than 100 items can't be displayed

---

app/server/server.py
app/tests/server/test_server.py

Added more exception handling to the AWS parsing to give us more information when there is an error posting an event. Right now, it says that there is an error posting the event but not much more detail is given as to why. Hopefully with the new changes, it will be more informative and useful 🤞

Adding more exception handling to inform whenever there is an error posting an AWS event

---

.github/workflows/labels.yml
.github/workflows/log_workflow_error.yml

Closes [Issue #439](https://github.com/cds-snc/site-reliability-engineering/issues/439) Github action to record that a workflow has failed. I am putting all the workflows so that the PR fails for all the workflows in the repo. The output is supposed to look like the following:
If this works, we can roll it to other repos.

Github action to record workflow failure in PR

---

.github/workflows/build_and_deploy.yml
.github/workflows/ci_container.yml
app/Dockerfile
terraform/ecs.tf

This PR undoes #59 and #127 because of continued incompatibilities with the ARM64 architecture

feat: revert back to x86 from arm64

---

app/requirements.txt
app/requirements_dev.txt

Adding httpx to the requirements.txt as it is actually being used in the client code and not just for dev purposes. Ooops.... 😱

Adding module to requirements.txt

---

app/server/server.py

In production, logging via google was not working since it was redirecting the url to http instead of https. Http requests were being blocked by the load balancer. I have now fixed the redirect url to have https instead of http only for production.

Fixing logging in production (frontend)

---

.devcontainer/docker-compose.yml
app/server/server.py
app/tests/server/test_server.py

The following changes were done:
- Added environment variable for production/dev environment determination
- Modified the devcontainer docker-compose to include "dev" as the environment variable value
- Changed the login route to convert the request uri to https if it is in production
- Added a couple of unit tests to test the new login logic

Adding logic for production google login 

---

catalog-info.yml

Add backstage config file to the sre-bot to be able to ingest github data into Backstage.

Adding backstage catalog config file so that we can inject github data into Backstage

---

catalog-info.yml

Adding owner to the config file - the documentation does not state that it is required but apparently it is!

Adding owner to catalog file

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.devcontainer/maxmind-create.sh
frontend/package-lock.json
frontend/src/scenes/geolocate/index.jsx

Configured maxmind to run locally plus geolocation to work on production.

Fixing geolocation on production plus configuring maxmind to run locally

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml

Making the dynamodb creation of the databases work, plus fixing a new change that AWS introduced that the access key's and id can't no longer contain special characters since dynamodb local v2.0. Information regarding the proceeding can be found here:
- https://www.agiliztech.com/2023/07/12/amazon-dynamodb-local-v20-whats-new/#:~:text=Updated%20Access%20Key%20ID%20convention&text=The%20new%20convention%20specifies%20that,only%20allows%20letters%20and%20numbers.
- https://repost.aws/articles/ARc4hEkF9CRgOrw8kSMe6CwQ/troubleshooting-the-access-key-id-or-security-token-is-invalid-error-after-upgrading-dynamodb-local-to-version-2-0-0-1-23-0-or-greater

Fixing dynamodb local v2.0 change plus creating dynamodb tables at startup

---

app/server/event_handlers/aws.py

Changing the text type to mrkdwn so that the on-call people are tagged properly.

Changing text type to mrkdwn so that the users are tagged properly in message

---

app/commands/incident.py
app/integrations/opsgenie.py
app/server/event_handlers/aws.py
app/server/server.py
app/tests/commands/test_incident.py
app/tests/intergrations/test_opsgenie.py
app/tests/server/event_handlers/test_aws_handler.py
app/tests/server/test_server.py

Adding opsgenie alert integration for the sre bot. Whenever a secret is detected, the SRE bot will send an alert to Opsgenie:
Also fixed an error that was appending the ignore and incident buttons twice when a url preview was crawled by Slack.

Adding opsgenie alert integration

---

.github/workflows/ci_code.yml
app/commands/incident.py
app/tests/commands/test_incident.py
app/tests/server/event_handlers/test_aws_handler.py

Changing the API key to a variable in order to stop the constant fake alerting. Also fixed a bug where the preview was messing up with the Incident/Acknowledge & Ignore buttons.

Changing the notify api key to a variable in order to stop alerting

---

.github/workflows/ci_code.yml
app/integrations/notify.py
app/requirements.txt
app/requirements_dev.txt
app/server/event_handlers/aws.py
app/tests/intergrations/test_notify.py
app/tests/server/event_handlers/test_aws_handler.py

Uses the Notify API endpoint to automatically revoke an API key that has been compromised.  Right now, when an API key has been compromised, the API endpoint will be called and the key will be automatically revoked. 
I left the code in the opsgenie integration so that we will have the ability to create an alert if needed in the future.
We will just have to wait to merge this PR when prod credentials are generated and we can update them in the env. variables here.

Use Notify API endpoint to automatically revoke a key

---

scripts/google_pickle_string/get_google_pickle_string.py
scripts/google_pickle_string/requirements.txt

Update the pickle string scope to be all Google Drive items.  This is being done as we're relying on the explicit permissions of the SRE Bot Google user to grant access to the bot.

fix: update pickle string scope

---

app/commands/incident.py

Update the messages added to a new incident channel to remind teams to stop any planned penetration or performance testing.  The notes will now look like so:
- Closes cds-snc/platform-core-services#513

fix: update incident channel notes for testing

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml
terraform/alarms.tf
terraform/local.tf
terraform/queries.tf
terraform/sns.tf
terraform/variables.tf

Closes #331 
Adding alarms to the SRE bot to detect any abnormal activity of Errors or Warnings. The alarm notifications will go into the #internal-sre-alerts channel.

Adding alarms to the SRE Bot so that we can get alerting when something goes wrong

---

.github/workflows/ci_container.yml
terraform/alarms.tf

Changing the alarms to pick up on Errors logged from the sre bot application and not all errors. If you do all errors, it picks up from the alarm name when it is alerting.

Fix circular reference of alarms

---

terraform/alarms.tf

Terraform apply failed when I merged my previous PR because it did not like the ```:``` in my pattern. This PR fixes the issue  by changing the pattern.

Tweaking log metric filter pattern

---

app/commands/incident.py
app/tests/commands/test_incident.py

Closes #342 
Fixing up a bug that if someone is already in a channel and the sre bot tries to invite them again, an error is generated and subsequent calls don't get executed.

Fixing up a bug where if the incident creator is in the channel, then don't invite them again 

---

app/commands/helpers/incident_helper.py
app/commands/utils.py
app/tests/commands/test_utils.py

The command /sre incident stale was not working as it was not listing all the stale incidents. This was a weird bug/result due to the way the Slack API was handling limits and channels. In order to get all the channels, you had to get a smaller subset of results and then iterate through the collection. Now all stale incidents are obtained and shown in the command. Stale incidents are defined as having no activity for more than 14 days.

Fixing up stale incidents not displaying

---

app/commands/incident.py

Closes #358 
Rewriting this code since we could have a situation where the app_unfurl_url does not exist.

Accounting for condition where app_unfurl_url does not exist

---

app/commands/helpers/incident_helper.py
app/tests/commands/helpers/test_incident_helper.py

Update the archive channel action to log the request details to Sentinel.

chore: log the archive incident channel actions

---

app/commands/helpers/incident_helper.py
app/commands/incident.py
app/integrations/google_drive.py
app/tests/commands/helpers/test_incident_helper.py
app/tests/intergrations/test_google_drive.py

Closes #355 
A new command for the SRE bot that closes an incident channel. To run it, you need to go to the incident channel and type ```/sre incident close```
Once this is done, the incident document is updated to "Closed", the incident spreadsheet for that particular channel is also updated to "Closed" and the channel is archived.

Close incident command 

---

app/commands/helpers/incident_helper.py
app/tests/commands/helpers/test_incident_helper.py

Send a message visible only to the user if the ```/sre incident close`` command is not ran in an incident channel. If it is not ran in an incident channel, the message will be as follows:

Send message to user if the close incident command is not ran from an incident channel

---

app/integrations/opsgenie.py
app/jobs/scheduled_tasks.py
app/tests/intergrations/test_opsgenie.py
app/tests/jobs/test_scheduled_tasks.py

Add an integration test for Opsgenie that checks every 5 minutes if the bot is able to interact with the Opsgenie API.
If the health check fails, an `ERROR` will be logged which will trigger a CloudWatch alarm.
- https://github.com/cds-snc/sre-bot/issues/365

feat: add Opsgenie integration test

---

app/integrations/opsgenie.py
app/jobs/scheduled_tasks.py
terraform/alarms.tf

Update to an API entpoint that the bot's Team API key can access.
Move the API call into the try block so that a request failure is
properly identified as a failed healthcheck.
Update the CloudWatch alarms to trigger more generically for errors, warnings
and exceptions.
- https://github.com/cds-snc/sre-bot/issues/365

fix: opsgenie integration healthcheck

---

app/integrations/google_drive.py
app/integrations/maxmind.py
app/jobs/scheduled_tasks.py
app/tests/intergrations/test_google_drive.py
app/tests/intergrations/test_maxmind.py
app/tests/jobs/test_scheduled_tasks.py

Add integration health checks for Google Drive and Maxmind.
- Closes https://github.com/cds-snc/sre-bot/issues/365

feat: add Google Drive and Maxmind healthchecks

---

app/commands/helpers/incident_helper.py
app/tests/commands/helpers/test_incident_helper.py

Added more logging to when the archiving of the channel fails so that we can gain visibility in the channel and the error message. Added a unit test as well to test the new code.

Adding more logging when the archiving of the channel fails

---

app/integrations/google_workspace/google_docs.py
app/tests/integrations/google_workspace/test_google_docs.py

Setting up the Google Docs functions to be used in the other modules/features

feat: setup Google Docs functions

---

app/integrations/google_workspace/google_docs.py

Fixing issue raise by @sylviamclaughlin on missing error handling!

fix: add missing error handler

---

app/commands/incident.py
app/commands/utils.py
app/tests/commands/test_incident.py
app/tests/commands/test_utils.py

Added logic to replace the user ids properly when tagging someone in Slack using @user_name. 
Now instead of "Hi <@U12345>, meet <@U67890> and <@U54321>", it will be written in the document as "Hi @user, meet @user and @user"

Adding logic to properly translate Slack usernames to the incident timeline

---

app/integrations/sentinel.py

Update the `log_to_sentinel` method so that on failure, it logs an error but does not bubble the exception up to the caller. This is being done because a failure to log to Sentinel should not break the SRE Bot's behaviour.
The logged error will get caught by the CloudWatch metric filter and allow the SRE team to investigate.

fix: stop log to sentinel from triggering Slack retries

---

app/server/event_handlers/aws.py
app/tests/server/event_handlers/test_aws_handler.py

Update the SRE bot to recognize and ignore spend budget auto-adjustment notifications.  We're receiving these now because of the historical spend budget setup on Notify production.
- https://gcdigital.slack.com/archives/C0388M21LKZ/p1709260800376949

fix: handle budget auto-adjustment events

---

app/integrations/google_drive.py
app/modules/incident/handle_slack_message_reactions.py
app/modules/incident/incident.py
app/tests/intergrations/test_google_drive.py
app/tests/modules/incident/test_handle_slack_message_reactions.py
app/tests/modules/incident/test_incident.py

Closes #418 
Improvements to the 💾 emoji to save to the incident document. Changes include:
1. Added a new ➡️ emoji to separate entries.
2. Made the time/date a link to the original message in Slack. 
Now the incident document looks similar to this:

Floppy disk save emoji improvements

---

app/integrations/slack/users.py
app/modules/incident/incident.py
app/tests/integrations/slack/test_users.py

Closes #426 
Fixed a bug with the SRE bot where the 💾 emoji was not translating user handles properly in the messages.

Fixing a bug with the SRE bot where the user handles were not translated properly

---

app/models/webhooks.py
app/modules/sre/webhook_helper.py
app/server/server.py
app/tests/models/test_webhooks.py
app/tests/modules/sre/test_webhook_helper.py
app/tests/server/test_server.py

The following changes were made:
1. Properly disabled a webhook. 
2. The message that now appears shows properly when disabling a webhook (ie it says Webhook disabled by user) and when enabled now says Webhook enabled by user. It was reverse prevously.
3. If a webhook is disabled, you will not be able to use it to send messages.
4. Unit tests were added and changed. 
Part of this PR closes #436

Disable a webhook 

---

app/modules/incident/incident_helper.py

Totally my fault here - at the last minute I decided to change the logic to make the code better thus breaking the intention and functionality of the code. The issue was that the message has to be sent before the channel is archived otherwise, the message would fail. As a result, I had to move the code that posts the message before the archiving action.

Fixing a bug where the person closing the incident was not displaying

---

app/integrations/google_workspace/google_calendar.py
app/modules/incident/incident_helper.py
app/tests/integrations/google_workspace/test_google_calendar.py
app/tests/modules/incident/test_incident_helper.py

Adding an input field to allow a user to input a number of days field to begin looking for first available time. The dialog now looks like the following:

Adding days input variable to let user select the number of days ahead to schedule a retro

---

app/modules/incident/incident.py
app/tests/modules/incident/test_incident.py

Added logic so that the Security team + Calvin does not get automatically added when we are testing creation of an incident.

Adding logic that the security team does not get automatically added when creating a test incident

---

app/jobs/notify_stale_incident_channels.py
app/modules/incident/incident_helper.py
app/tests/jobs/test_notify_stale_incident_channels.py
app/tests/modules/incident/test_incident_helper.py

Change the Stale notification message to now include a button to schedule a retro. The new layout looks like this:
It might be too verbose or too big - any suggestions on how to improve it will be appreciated. Also, not sure about the French translations 😬

Add a scheduling button to the Stale channel notificaiton

---

app/integrations/google_workspace/google_service.py
app/tests/integrations/google_workspace/test_google_service.py

New:
- reusable function to execute google api calls
- handles pagination for methods that support it
- supports use of kwargs so that optional parameters in google api methods can be fully leveraged
- function to convert snake_case strings to camelCase.
- Purpose is to handle the conversion of parameters passed to the execute google api call since the API expects parameters as camelCase whereas most of the parameters in the modules are snake_case.

feat: setup execute google api call function & tests

---

app/integrations/google_workspace/google_calendar.py
app/tests/integrations/google_workspace/test_google_calendar.py

Quick fix:
the Calendar Event  insert method doesn't handle the toiso() function, it expects a string directly.

fix: remove datetime format fn

---

app/integrations/slack/users.py
app/tests/integrations/slack/test_users.py

New integration funciton: get the email address from the slack user executing the command.
To be used in conjunction with the insert event: 
if a user kicks off the retro command, they can be the organizer of the event and will be able to modify the event in their own calendar

feat: get slack user's email

---

.github/workflows/build_and_deploy.yml
.github/workflows/ci_container.yml
.github/workflows/refresh_geodb.yml
Dockerfile

Move the GeoDB data refresh job outside of the container build process

feat: hoist the refresh geodb outside of the Dockerfile

---

.github/workflows/build_and_deploy.yml
.github/workflows/ci_container.yml
Dockerfile

Updating the workflows and the Dockerfile as the initial tar file included the path with the db data.
This update workflow should properly get the tar file without including the path.

fix: initial upload of the file with directory

---

app/modules/incident/schedule_retro.py

Fixing up calendar scheduling. It was previously using the date time and the time object was messing up the scheduling based on the time you were trying to schedule it. With the fix, it puts the time to midnight.
I guess my timezone testing was not allowing me to have issues since I was testing after 4pm each time 😓

Fixing up calendar scheduling

---

app/integrations/google_workspace/google_calendar.py
app/tests/integrations/google_workspace/test_google_calendar.py

This PR allows anyone to reschedule the calendar event if required. Previously, guests were not allowed this.

Allow guests to modify calendar events

---

app/integrations/aws/client.py
app/integrations/aws/identity_store.py
app/integrations/utils/api.py
app/tests/conftest.py
app/tests/integrations/aws/test_client.py
app/tests/integrations/aws/test_identity_store.py
app/tests/integrations/utils/test_api.py

- Add functions to handle conversion of snake case to pascal case
- Fix client to convert kwargs with pascal case (instead of camel case like Google client)
- Add functions to handle groups, groups memberships, users and grouping of the 3 objects together
- Add global fixtures to handle Google and AWS API in tests

Fix/aws integration for client & identity store

---

app/integrations/google_workspace/google_calendar.py
app/modules/incident/incident_helper.py
app/modules/incident/schedule_retro.py
app/tests/integrations/google_workspace/test_google_calendar.py
app/tests/modules/incident/test_incident_helper.py
app/tests/modules/incident/test_schedule_retro.py

This PR adds functionality to attach the incident document to the meeting invite.

Attach incident document to retro invite

---

app/integrations/google_workspace/google_calendar.py
app/tests/integrations/google_workspace/test_google_calendar.py

Additional tweaks for the calendar functionality dealing correctly with timezones. This "should" fix all the issues that we have encountered and any edge cases🤞

Additional fixes for edge cases and for correct timezones

---

app/integrations/google_workspace/google_calendar.py
app/requirements_dev.txt
app/tests/integrations/google_workspace/test_google_calendar.py

Adding functionality to automatically skip federal holidays when scheduling a retro. The SRE bot will basically not schedule any retros on any public holiday days. This uses Paul Craig's holiday API at https://canada-holidays.ca/

Skip federal holidays when automatically scheduling a retro

---

app/integrations/aws/client.py
app/integrations/aws/identity_store.py
app/jobs/scheduled_tasks.py
app/tests/integrations/aws/test_client.py
app/tests/integrations/aws/test_identity_store.py
app/tests/jobs/test_scheduled_tasks.py

Tentative fix for the healthcheck (limited permissions for the bot)

fix: use list users as healthcheck

---

app/modules/incident/incident.py
app/tests/modules/incident/test_incident.py

Previously, forwarded messages were not handled properly by the incident timeline. This PR resolves this issue and now forwarded messages that have the 💾 emoji appear as such:

Adding a fix for forwarded messages in incident timeline

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/maxmind-create.sh
.vscode/settings.json
app/Makefile
app/requirements.txt
app/requirements_dev.txt

- Update the to most recent version of devcontainers image
- Remove optional install steps from Dockerfile to speed up build (moved to features and requirements files instead)
- point aws_completer to path matching the features installed location
- Make db and maxmind create scripts callable once logged in AWS (fetch DB file from S3 bucket instead of calling the API each time)
- Move vscode settings to devcontainer.json file
- Add dev-setup command to go through each steps needed to run the dev server

Feat: bump devcontainer image and simplify build steps

---

app/requirements.txt
app/server/server.py
app/tests/server/test_server.py

Add rate limiting to the SRE bot's endpoints to increase security. We are excluding custom headers passed by Sentinel. 
If you think I should increase/decrease the rate limits, let me know.

Add Rate limiting to the SRE bots endpoints

---

app/server/server.py
app/tests/server/test_server.py

Remove the rate limiting for this as we are getting this error message and we will need to investigate what is calling it:
```ERROR:slowapi:Skipping limit: 20 per 1 minute. Empty value found in parameters.```

Removing the rate limiting for the geolocate function

---

.github/workflows/pr_notify_slack.yml

Workflow to post to the #sre-tech-ops channel whenever a new PR is created in the repo and the reviewers are internal-sre. The workflow will post to the channel with information similar to the following:

Adding workflow to notify the #sre-tech-ops channel when new PR is created

---

app/server/server.py
app/tests/server/test_server.py

Adding a login required decorator so that we can secure certain API endpoints. If we add this decorator to an API endpoint, the user has to be logged in, in order to use that particular endpoint.

Adding a login required decorator to secure certain api endpoings

---

app/integrations/aws/ogranizations.py
app/tests/integrations/aws/test_organizations.py

Adding an AWS Organizations integration in order to be able to get a list of AWS Accounts.

Adding an Integration for AWS Organizations

---

terraform/templates/sre-bot.json.tpl

Adding the host port and protocol to the ECS task definition so that it does not get reset in a terraform plan.

Adding host port and protocol to the ECS task definition

---

app/integrations/google_workspace/google_calendar.py

Fix a bug where the returned result can be a tuple instead of a dict.

Fixing up a bug where the returned result can be a tuple

---

app/requirements.txt
app/server/server.py
app/server/utils.py
app/tests/server/test_server.py
app/tests/server/test_utils.py

Adding JWT token that would expire after 30 minutes so that we can secure some of the endpoints. In order to request access, you the session user + JWT token will be checked.

Adding JWT token and session checking api authentication

---

app/server/server.py
app/server/utils.py
app/tests/server/test_utils.py
frontend/src/components/AWSRequestForm.jsx
frontend/src/scenes/logout/index.jsx

Making changes to set the jwt token in the user's browser cookie. The jwt token expires after 30 minutes and gets deleted when the user logs out.

Setting the jwt_token in the cookie

---

app/integrations/google_workspace/google_calendar.py
app/modules/incident/incident.py
app/modules/incident/incident_helper.py
app/modules/incident/schedule_retro.py
app/tests/integrations/google_workspace/test_google_calendar.py
app/tests/modules/incident/test_incident.py
app/tests/modules/incident/test_incident_helper.py
app/tests/modules/incident/test_schedule_retro.py

The following changes have been made to the calendar event functionality:
- The description when you create an incident is now part of the description of the incident channel
- The description above is taken as the title of the calendar invite
- After a calendar invite is created, it is posted in the channel with event details:

Using description as calendar event title and posting notification message to Slack with event info

---

.github/workflows/ci_code.yml
app/modules/incident/incident.py
app/tests/modules/incident/test_incident.py

The proper command to be used here is setPurpose as opposed to setDescription.

Adding files to fix an issue with creating incidents

---

app/integrations/aws/identity_store.py
app/tests/integrations/aws/test_identity_store.py

Fixing Identity store integration by passing the role ARN parameter to assume when performing the api call.

fix: set role arn in execute api call params

---

app/modules/dev/aws_dev.py
app/modules/incident/incident_helper.py
app/tests/modules/incident/test_incident_helper.py

Making the channel name be the event title when scheduling a retro.

Channel name is now the event title for the retro

---

terraform/waf.tf

Put in terraform the WebACL for SRE bot. Also, add a feature so that if 1000 requests from the same IP address come within 5 minutes, block that IP address. We can delete the existing one after since it was put together for testing.

Create WebACL for SRE bot. 

---

app/modules/aws/aws_account_health.py

The client.views_open method was timing out and raising a expired trigger error.
This fix opens up the health modal right away and updates it once the data actually is received.

fix: use modals' views update to manage delay

---

app/modules/aws/aws_account_health.py

Remove the duplicate account ID from the modals

fix: remove duplicate account ID from modal

---

app/modules/incident/incident_helper.py
app/tests/modules/incident/test_incident_helper.py

fixing the trigger ID expiring when open modal takes more than 3 seconds

fix: schedule retro trigger ID expiry

---

terraform/waf.tf

Changing the name of the waf group to have a specific format as required by the documentation - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_logging_configuration

Changing the name of the log group

---

app/integrations/google_workspace/google_docs.py
app/integrations/google_workspace/google_drive.py
app/integrations/google_workspace/google_service.py
app/integrations/google_workspace/sheets.py
app/modules/incident/incident_helper.py
app/tests/integrations/google_workspace/test_google_drive.py
app/tests/integrations/google_workspace/test_google_service.py
app/tests/integrations/google_workspace/test_sheets.py
app/tests/modules/incident/test_incident_helper.py

- Refactor the incident helper (used with `/sre incident` command) to use generic Google integrations modules instead of the catchall google_drive module (became a very large file with lots of process specific configuration)
- Introduce the Google Sheets module
- Add typing annotations when possible
Additional fixes:
- Refactoring required some updates to the execute api function, namely supporting the `fields` argument as a supported parameter in the api calls.
- Google Drive and Docs also were updated to support fields as an arg
- Delegated user email has been added to functions with write permissions so that they can possibly be executed by using the caller's identity instead of the bot's, thus inheriting their permissions in Google Workspace

Feat/refactor incident helper with integrations 

---

app/modules/incident/incident_document.py
app/modules/incident/incident_folder.py
app/modules/incident/incident_helper.py
app/modules/incident/incident_roles.py
app/tests/modules/incident/test_incident_document.py
app/tests/modules/incident/test_incident_folder.py
app/tests/modules/incident/test_incident_helper.py
app/tests/modules/incident/test_incident_roles.py

migrate roles, docs and folders specific functions into distinct modules
fix: add support for the `/sre incident roles` command in incident-dev- channels (for dev purposes)

Feat/isolate incident roles, docs and folders concept into modules

---

app/modules/incident/incident_alert.py

Need to import the modules.incident.incident to properly resolve the functions.
Probably should rename the main incident module as core to avoid such import issues.

fix: import needs to import the incident module

---

app/server/server.py

Adding more detailed logging to debug the payload errors generated by the Upptime status notification

fix: add detailed payload logging for debugging

---

app/modules/role/role.py
app/tests/modules/role/test_role.py

Adding a new document to the templates for the talent role.

Adding new document to the templates for the command role

---

terraform/alarms.tf
terraform/local.tf
terraform/queries.tf

Setup an alarm if the scheduler's job didn't log at least once every 5 minutes. Set the eval period to 10 so that it doesn't go off all the time if something happened
Fixes #350

feat: setup an alarm when no log within 5 mins

---

app/jobs/scheduled_tasks.py

Add a try/except statement to wrap the jobs to avoid having errors break the scheduler

Fix: add a error handling function to jobs

---

terraform/iam.tf
terraform/sqs.tf

Adding an SQS FIFO queue plus a dad letter queue to store unprocessed messages for the SRE bot. The use case is for the 💾 emoji to send and process messages using the queue.

Adding SQS to manage messages in the SRE bot

---

app/integrations/google_workspace/google_service.py
app/tests/integrations/google_workspace/test_google_calendar.py
app/tests/integrations/google_workspace/test_google_drive.py
app/tests/integrations/google_workspace/test_google_service.py

- Modify the Google api error logging to add more context to the error
- Add a non-critical list of known, recurring errors to reduce the noise in logs errors.

Fix: add more details in error logging

---

app/modules/role/role.py
app/tests/modules/role/test_role.py

The template file was renamed thus we need to update it in the code. Could think of better way to get this automatically but the file name does not change often and it needed a rewrite which can be done at a later time.

Renaming Template file

---

terraform/ecs.tf
terraform/variables.tf

We have had recently had memory spikes that had killed the SRE bot. I am scaling the SRE bot to increase the number of ECS tasks and the memory of the container.

Increasing memory and number of tasks to 2 for SRE bot

---

.github/workflows/build_and_deploy.yml
.github/workflows/docker_vulnerability_scan.yml

Update the Docker scan actions to use a self-hosted Trivy vulnerability database. This is being done to address the rate limiting of the publicly hosted database.
- https://github.com/cds-snc/platform-core-services/issues/597

fix: use CDS Trivy vulnerability database

---

terraform/alb.tf

Update to the latest recommend ALB SSL policy which is FIPS 140-3 compliant.

chore: upgrade ALB to recommend SSL policy

---

app/tests/integrations/google_workspace/test_google_calendar.py

Updating the unit tests to not have the year hard coded. Since switching to 2025, the tests broke 🫠

Updating the unit tests to not hardcode the year

---

app/integrations/google_workspace/google_directory.py
app/tests/integrations/google_workspace/test_google_directory.py

Optimize the Google Workspace list_groups_with_members method to use list_users instead of querying the Google API for individual users' details.
Average Time to run for all AWS-* groups (67 groups as of today:
- Previous: 165.4 secs
- New: 23.6 secs

Refactor group member retrieval to use list_users for user details

---

app/integrations/google_next/directory.py
app/integrations/google_next/service.py
app/tests/integrations/google_next/test_directory.py

Update the Google Next `list_users` method than we used with the refactored version in the Google Workspace integration.

feat: refactor list groups with members to use list_users

---

app/requirements.txt
app/requirements_dev.txt
app/tests/server/test_server.py

With httpx version 0.27.0 version, the app parameter was deprecated in AsyncClient. This code fixes the issue and we upgraded tot he latest version of httpx. Also, moved httpx to the requirements-dev file since it is used only for unit testing. 
Detail of issue can be found [here](https://github.com/encode/starlette/issues/2524)

Unit test changes due to changes in httpx module

---

app/integrations/google_next/directory.py
app/tests/integrations/google_next/test_directory.py

Refactored the Google Next Directory module as a helper class.
- Google Directory is now a class
- State is preserved so the authenticated service can be created once and used multiple times before being closed
- Clarified use of these helper classes: the hoisted methods make it easy to use through the code base but it is possible to simply use the Service's `get_google_service` and use the [regular approach described in the documentation](https://googleapis.github.io/google-api-python-client/docs/pagination.html)

refactor: Directory module's functions into class

---

app/requirements.txt
app/requirements_dev.txt

To fix incident where the httpx needed to be moved to the requirements.txt.

Moving the httpx library to requirements instead of requirements-dev

---

terraform/alarms.tf
terraform/ecs.tf

Adding deployment alarm to the SRE bot. Created the alarm using the recommendations outlined here - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-alarm-failure.html

Adding deployment alarm to SRE bot

---

terraform/alarms.tf

Tweak the alarm settings to detect deployment failures.

Tweaking alarm settings

---

terraform/iam.tf

fix: add permission for the incidents table

---

app/modules/incident/incident.py
app/tests/modules/incident/test_incident.py

Attach canvas to an incident channel by default when an incident channel is created. 
With a canvas, you can store a lot of different information: 
When a change is made to the canvas, it is announced in the channel so that everyone knows:

Attach canvas to incident channel 

---

.github/workflows/build_and_deploy.yml

Modify the build and deploy workflow to report the deployment to the internal SRE alerts channel regardless if successful or failure.

Adding steps to report failure or successful deployment to Slack

---

app/tests/modules/incident/test_incident.py

Fix the dynamodb patch path to avoid creating mocked items in the prod DB

fix: dynamodb patch path

---

.github/workflows/build_and_deploy.yml

Adding a sleep cycle of 5 minutes to the ecs wait task since there is no native way to increase the timeout to more than the default 10 minutes. 
Issue is documented [here](https://github.com/aws/containers-roadmap/issues/2474) and it is on the roadmap (ie to increase timeout limit)

Adding 5 minute sleep cycle to ecs wait

---

app/modules/incident/incident.py
app/modules/incident/incident_folder.py
app/modules/incident/incident_helper.py
app/tests/modules/incident/test_incident_folder.py
app/tests/modules/incident/test_incident_helper.py

Added two new commands to the sre incident bot:
1. /sre incident add_summary
This opens a text box and an Incident Commander can put text into it around the current summary of the incident
2. /sre incidentsummary
This will post the current summary into the incident channel
1. Run the dev sre bot
2. call /dev-sre incident add_summary
3. call /dev-sre incident summary
4. You should be able to add a summary for the incident as well as see a summary for the incident

Add summary command

---

app/modules/incident/incident_roles.py
app/tests/modules/incident/test_incident_roles.py

Channel description is now updated if the `/sre incident roles` command is used. The following things happen:
- A message is sent to the channel that the IC and OL have been updated (this was existing functionality):
- The channel description has been updated to include the IC/OL:
- A message is sent to the channel indicating the the incident description has been changed:

Adding code to add the IC/OL to the Channel description

---

app/tests/integrations/google_workspace/test_google_calendar.py

This unit test failed due to daylight savings time (failed action run can be seen here - https://github.com/cds-snc/sre-bot/actions/runs/13748582910/job/38446650973?pr=781). I am changing the unit test so that it works regardless of time changes.

Modifying unit test so that it does not break with DST

---

app/core/config.py
app/integrations/aws/client.py

Renaming the AWS settings env vars used for known error handlings

Refactor/aws error handling: rename error lists for consistency

---

app/modules/incident/incident.py

This small fix should normally handle the odd behaviour we saw where a user had trouble launching an incident

fix: handle nonetype warning detected when modal is loading

---

app/modules/incident/incident.py
app/tests/modules/incident/test_incident.py

Small fix to ensure security users addition logic is only processed if the response has been updated with actual users.

fix: NoneType error on security_users if not security incident

---

app/modules/incident/information_display.py
app/tests/modules/incident/test_information_display.py

Small fix for the issue found in the Incident modal where the report URL is already the full link to the report. The issue was that it was assuming getting the document ID instead so the page wouldn't work

fix: update report URL formatting in incident information view

---

app/modules/incident/incident_helper.py
app/tests/modules/incident/test_incident_helper.py

This pull request enhances the incident command helper by adding French language support for help text and commands. 
The key changes include splitting the French help text in a distinct output so that it better fits in Slack UI, updating help command logic to support French, and expanding tests to cover the new functionality.

Feat: update help command to support French language

---

app/api/v1/routes/webhooks.py

Hotfix: handle missing hook_type webhooks

fix: handle webhooks without hook_type status
