.github/workflows/ci_code.yml, app/Makefile, app/commands/sre.py, app/requirements_dev.txt, app/tests/commands/test_sre.py, terraform/oidc_role.tf
=> fix: python ci

terraform/ecs.tf
=> fix: add task role arn

.github/workflows/build_and_deploy.yml, app/commands/helpers/webhook_helper.py, app/requirements_dev.txt, app/tests/commands/helpers/test_webhook_helper.py
Closes #14 by adding stats for webhooks to the list output.
=> feat: reformat list output to include stats

app/commands/helpers/incident_helper.py, app/commands/helpers/webhook_helper.py, app/commands/sre.py, app/tests/commands/helpers/test_incident_helper.py, app/tests/commands/helpers/test_webhook_helper.py, app/tests/commands/test_sre.py
This PR fixes an issue were help text was not echoed back properly.
=> fix: responses for help text

README.md
Adding basic docs for local development.
Look up the README.md file.
=> feat: Add basic dev documentation

app/server/event_handlers/aws.py, app/tests/server/event_handlers/test_aws_handler.py
This PR adds the ability for a webhook to handle a budget alert notification through SNS.
=> feat: adds the ability to handle budget alerts

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
This PR makes the feature set in the container flexible for other architectures
=> feat: make dev container flexible for other archs

.github/workflows/build_and_deploy.yml
Forgot to update this when I deleted this role
=> fix: use new OIDC admin role

.devcontainer/devcontainer.json, .github/workflows/build_and_deploy.yml, .github/workflows/ci_container.yml, app/Dockerfile, terraform/ecs.tf
This PR switches the SRE Bot to use an ARM based image in Fargate
=> feat: switch to ARM image

.devcontainer/dynamodb-create.sh, terraform/dynamodb.tf
This PR adds a new global table for the SRE Bot
=> feat: add new global table for SRE bot

.github/workflows/tf_plan.yml
Replace the existing terraform plan workflow with one that is hosted at
github.com/cds-snc/workflows this is just a test to see if this will
work for CDS.
Related to: https://github.com/cds-snc/workflows/issues/2
=> feat: use shared workflow for tf plan

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml
use role_arn instead of role name as well
=> feat: use centralized terragrunt apply

app/commands/incident.py
=> fix: truncate Google Meet link

.github/workflows/export_github_data.yml
Adds the new GitHub Metadata exporter
=> feat: add GitHub metadata exporter

.devcontainer/Dockerfile, .devcontainer/docker-compose.yml
Closes #91 by upgrading the dev containers to python 3.11 after the app was already running on 3.11
https://github.com/cds-snc/sre-bot/blob/main/app/Dockerfile#L1
=> feat: upgrade to python 3.11

.github/workflows/ossf-scorecard.yml
This PR adds common metadata to the OSSF results file using `jq`.
=> feat: add common metadata to results file

.github/workflows/ossf-scorecard.yml
This PR fixes the JQ compression for the OSSF report.
=> fix: compression

.github/workflows/build_and_deploy.yml, .github/workflows/docker_vulnerability_scan.yml
Scan the SRE bot Docker image for vulnerabilities and publish an SBOM of its assets to the repo's dependency graph.
=> feat: Docker SBOM and vulnerability scan

app/commands/incident.py, app/tests/commands/test_incident.py
Updated path to user id from body
=> Fix: Incident but by updating user_id path

app/server/event_handlers/aws.py, app/tests/server/event_handlers/test_aws_handler.py
Logic and unit tests for the SRE bot formatting of messages that are coming from the auto mitigation account settings. 
Closes #144
=> SRE bot logic to properly format messages from the auto-mitigation of security groups opening up ports 22 and 3389

app/Makefile, app/commands/helpers/incident_helper.py, app/commands/incident.py, app/main.py, app/pytest.ini, app/tests/commands/test_incident.py, app/tests/server/test_server.py, app/tests/test_main.py
This PR fixes the change in the upgrade to starlette around middleware and also the slash command
=> fix: middleware and slash command

app/server/event_handlers/aws.py
A super small layout change to display the new user created notification message in slack.
=> Small layout change

.github/workflows/bandit_security_scan.yml, .github/workflows/build_and_deploy.yml
Adding Max's new DNS audit action to a few github actions to testing.
=> Adding dns data audit action for github actions

.github/workflows/bandit_security_scan.yml, .github/workflows/build_and_deploy.yml, .github/workflows/ci_code.yml, .github/workflows/ci_container.yml, .github/workflows/docker_vulnerability_scan.yml, .github/workflows/export_github_data.yml, .github/workflows/labels.yml, .github/workflows/log_workflow_error.yml, .github/workflows/ossf-scorecard.yml, .github/workflows/s3-backup.yml, .github/workflows/shellcheck.yml
Adding DNS proxy action to audit DNS requests to github actions.
=> Adding dns proxy action to all github actions

frontend/src/App.js
This PR addresses a bug where the login page was flashing the dashboard page at page loading due to a race condition.
=> Fixing up race condition where the login page was flashing at initial loading

frontend/package-lock.json, frontend/package.json, frontend/src/scenes/geolocate/index.jsx
Added the geolocation page so that you can geolocate an IP address. If the address is valid, the address will be displayed along with a red dot to indicate its location. If it is not a valid address, an error message will be displayed. 
Initial screen: 
Succesful lookup:
Invalid IP/Other error:
When hovering over map:
=> Geolocation page

frontend/src/scenes/geolocate/index.jsx
The api endpoint was not working production due to the relative path not being called. This fixes up the issue.
=> Fixing up the relative paths in production

frontend/README.md
This PR adds `npm install` in the README file.
=> Add instruction in README

.devcontainer/dynamodb-create.sh
=> skip dynamodb table creation if it already exists

.devcontainer/devcontainer.json, terraform/alb.tf
Update the LB configuration to enable delete protection. This will stop accidental deletion of the LB.
- https://github.com/cds-snc/platform-core-services/issues/471
=> fix: enable load balancer delete protection

.gitignore, scripts/google_pickle_string/get_google_pickle_string.py, scripts/google_pickle_string/requirements.txt
Adds the get_google_pickle_string.py script that we copied from [the Azure Sentinel repo](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/GoogleWorkspaceReports/Data%20Connectors/get_google_pickle_string.py) with the modified scopes.
=> feat: add the code for generating the google pickle string

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, terraform/ecs.tf, terraform/iam.tf, terraform/ssm.tf, terraform/templates/sre-bot.json.tpl, terraform/variables.tf
Update the ECS task to retrieve the Google OAuth pickle string from SSM ParameterStore.
=> feat: add Google OAuth pickle string

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml
Update the TF workflows so they only trigger when files that impact AWS resources are changed.
=> fix: update the Terraform workflow path triggers

.github/workflows/ci_container.yml
Remove the dive action from the container build github action.
=> Removing the dive action from the container build step

app/commands/incident.py
Added instructions to email CCCS/TBS (for now)/and security team for ICs.
=> Add more info to incident instructions

app/commands/role.py, app/tests/commands/test_role.py
Talent wants a new file called "Recruitment Feedback" to be copied over to the appropriate folder when creating a new role. This code takes care of this.
=> Adding a new template file to be copied to the role folder when creating a new role

app/modules/incident/incident_helper.py, app/tests/modules/incident/test_incident_helper.py
Adding exception handling and unit tests for handling Ephemeral messages.
=> Adding some exception handling for sending of Ephemeral message

terraform/iam.tf, terraform/s3.tf
- Setting up the AWS S3 bucket resource and policies to grant read/write permission to the bot
=> Feat/aws integration (infra)

README.md
Small update to help describe the refactoring changes that have been occurring
=> feat: update README with principles for refactor

app/modules/incident/incident.py, app/modules/incident/schedule_retro.py
Adding "dev" to incident channel when creating a channel via the sre-bot and fixing a bug with the calendar scheduling.
=> Fixing up a bug plus adding dev to channel

.github/workflows/refresh_geodb.yml, terraform/oidc_roles.tf
Fixing the geodb action error by granting proper permissions with dedicated role
=> fix: add permissions to workflow to put object in target bucket

.github/workflows/refresh_geodb.yml
=> fix: add permissions for workflow

.github/workflows/refresh_geodb.yml
Remove write permission to workflow since it's not going to write to the repo itself.
=> Fix: remove unnecessary permission

Dockerfile
Fixing the steps of the Dockerfile to take the extracted value in the subfolder and copy to the proper folder.
=> fix: Dockerfile steps to copy file from proper dir

app/integrations/aws/identity_store.py, app/tests/integrations/aws/test_identity_store.py
Add AWS function integration to:
- Add a user to a group
- Get group ID by name
- Remove a user from a group
=> feat: implement the user assignment to groups

app/integrations/google_workspace/google_calendar.py, app/integrations/utils/api.py, app/tests/integrations/google_workspace/test_google_calendar.py, app/tests/integrations/utils/test_api.py
Adding a google hangout link to the meeting invite (because I can't believe I did not notice this before 😱 )!!!
=> Adding google hangout link to the meeting invite

app/integrations/aws/client.py, app/integrations/aws/identity_store.py, app/tests/integrations/aws/test_client.py, app/tests/integrations/aws/test_identity_store.py
- Improve readability of the logs generated with AWS api error handler function
- Fixed handling of the AWS API responses, specifically around resources deletions where the response was supposed to be returning an empty dict but consistently includes the response's metadata.
=> fix: handling of AWS API responses

app/integrations/aws/identity_store.py
Small fix to ensure the api call properly works.
=> fix: use specific params to ensure API call doesn't fail with unused kwargs

app/tests/utils/test_filters.py, app/utils/filters.py
Small feature to help out when pre-formating list of objects
=> feat: add new function to help pre format a list of objects

.devcontainer/devcontainer.json
=> Revert "chore(deps): pin dependencies"

app/modules/provisioning/entities.py
Setup event logging on entity provisioning module
=> feat: log provisioning events to Sentinel

app/integrations/aws/client.py, app/modules/provisioning/groups.py, app/tests/integrations/aws/test_client.py
Small fix on the use of warning method instead of warn
=> fix: use warning method instead of warn

.devcontainer/Dockerfile, app/requirements.txt, app/requirements_dev.txt
Adding awscli since it is needed in the entry.sh script.
=> Adding awscli back in the requirements file. 

app/server/server.py, app/tests/server/test_server.py
Increase some of the rate limiting limits.
=> Increasing rate limiting

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/scenes/logout/index.jsx
Noticed that the logging out was not working as expected. This PR fixes this.
=> Fixing Logout

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/scenes/access/index.jsx, frontend/src/scenes/access/index.test.js, frontend/src/scenes/geolocate/index.jsx, frontend/src/scenes/global/Sidemenu.jsx, frontend/src/scenes/version/index.jsx
The following change have been made to the AWS Access page:
1. Added an accordion to request new AWS Access.
2.  Added an accordion to view current AWS requests that have not been reviewed.
3.  Added an accordion to view all past AWS Requests.
4. Added unit tests for the AWS access page. 
5.
=> Adding additional elements to the AWS access page

app/server/utils.py
The environment variables are not getting correctly loaded in utils.py and this should fix the issue.
=> Loading environment variables correctly in utils

app/integrations/aws/identity_store.py, app/tests/integrations/aws/test_identity_store.py
Fix the list_users function with role arn
=> fix: pass permission to assume role

app/integrations/slack/users.py, app/tests/integrations/slack/test_users.py
Fixing an issue where some Slack users email couldn't be found using their handle. Turns out that the users.list method returns all deleted users by default so we had more than 1000 users returned, which happens to be the limit per page.
=> fix: introduce method to paginate for users.list

app/jobs/scheduled_tasks.py
Small change on the healthcheck using the integrations (instead of the former catchall google_drive module) before further migrating away from the former way of making Google API calls (w/ pickle string)
=> feat: migrate to Google Workspace integrations

frontend/package-lock.json, frontend/package.json
Cleaning up npm packages that are unused.
=> Cleaning up unused packages

app/modules/incident/incident_conversation.py, app/tests/modules/incident/test_incident_conversation.py
I fixed a bug with the save emoji where it was not working properly for threaded messages and was not arranged in the correct chronological order.
=> Fixing up a bug with the incident threading and save emoji

app/jobs/scheduled_tasks.py
Fix the import statement of the method
=> fix: import method from module with same name

terraform/alarms.tf, terraform/local.tf, terraform/queries.tf
=> revert: alarm to avoid increase in cost

terraform/iam.tf
=> fix: typo in policy ARN

app/integrations/google_workspace/google_calendar.py, app/tests/integrations/google_workspace/test_google_calendar.py
Modifying code so that the scheduling retro times will be adjusted for daylight savings time.
=> Adding code to adjust for daylight savings time

app/integrations/utils/api.py, app/tests/integrations/utils/test_api.py
Slight improvement on the new retry_request function to more easily see when there were failed calls and retries.
=> feat: improve retry_request logging

app/modules/aws/aws.py
Noticed that this was wrong so I am changing it - super minor but threw me off yesterday.
=> Minor change to usage instructions

app/integrations/google_next/docs.py, app/tests/integrations/google_next/test_docs.py
Refactor the Google Docs functions as a class to store the authenticated service for potential performance gains.
=> feat: refactor Google Docs as a class

app/requirements.txt, app/requirements_dev.txt
Reverts cds-snc/sre-bot#716
In the name of science 🧪
=> Revert "Moving the httpx library to requirements instead of requirements-dev"

app/requirements.txt, app/requirements_dev.txt
Reverts cds-snc/sre-bot#718
I'm going to keep the PR title as is... 😆
=> Revert "Revert "Moving the httpx library to requirements instead of requirements-dev""

app/requirements.txt, app/requirements_dev.txt
=> Revert "Revert "Revert "Moving the httpx library to requirements instead of requirements-dev"""

app/requirements.txt, app/requirements_dev.txt
=> Revert "Revert "Revert "Revert "Moving the httpx library to requirements instead of requirements-dev""""

terraform/alarms.tf
Associating the cluster name and service and increasing the sensitivity of the alarms.
=> Tweaking alarm settings and adding the service and cluster name

app/server/server.py, app/tests/server/test_server.py
Small fix to avoid confusion with the Upptime Alerts
=> fix: update header of the status alert

app/modules/slack/webhooks.py, app/tests/modules/slack/test_slack_webhooks.py
Fix the dynamodb get_item return value when invoked by the slack webhooks integration.
=> fix: dynamodb get_item return value

app/tests/modules/incident/test_incident.py
Fix unit tests that are failing due to DynamoDB changes.
=> Fixing unit tests to account for the dynamodb changes

app/modules/incident/incident_folder.py, app/tests/modules/incident/test_incident_folder.py
Simple feature to retrieve an incident by the channel ID
=> feat: add fn to retrieve incident by channel ID

terraform/dynamodb.tf
Adding a backup to the DynamoDB database that will run every at 1:00am EST.
=> Adding backup plan for dynamodb

.github/workflows/build_and_deploy.yml
Update the workflow to use Success webhook if successful
=> Fix/update Slack webhook URL for successful ECS deployment notification

terraform/variables.tf
=> feat: increase cpu to 512

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
Adding new issue templates for a new feature and bug report.
=> Adding issue templates to the repo for new feature and bug report

.github/ISSUE_TEMPLATE/feature-request.yml
Small change to change the inputs to textarea.
=> Change inputs to textarea

app/core/config.py, app/core/logging.py, app/main.py, app/requirements.txt
- Introduce structured logger
- Improve config structure
- Update main.py with new logger and config
=> Refactor/issue 795/structured logging

app/core/config.py, app/core/logging.py, app/integrations/aws/client.py, app/integrations/aws/config.py, app/integrations/aws/cost_explorer.py, app/integrations/aws/dynamodb.py, app/integrations/aws/guard_duty.py, app/integrations/aws/identity_store.py, app/integrations/aws/lambdas.py, app/integrations/aws/organizations.py, app/integrations/aws/security_hub.py, app/integrations/aws/sqs.py, app/integrations/aws/sso_admin.py, app/main.py, app/tests/integrations/aws/test_client.py, app/tests/integrations/aws/test_identity_store.py
Refactor AWS Integrations package to use the structured logging and core config
Fixes #838 & #824
=> Refactor/config logging/aws integration

app/core/config.py, app/core/logging.py, app/integrations/google_next/directory.py, app/integrations/google_next/docs.py, app/integrations/google_next/service.py, app/integrations/google_workspace/gmail.py, app/integrations/google_workspace/google_calendar.py, app/integrations/google_workspace/google_directory.py, app/integrations/google_workspace/google_drive.py, app/integrations/google_workspace/google_service.py, app/integrations/google_workspace/sheets.py, app/tests/integrations/google_next/test_directory.py, app/tests/integrations/google_next/test_service.py, app/tests/integrations/google_workspace/test_gmail.py, app/tests/integrations/google_workspace/test_google_calendar.py, app/tests/integrations/google_workspace/test_google_directory.py, app/tests/integrations/google_workspace/test_google_drive.py, app/tests/integrations/google_workspace/test_google_service.py
Larger refactoring since we have a lot of integration with Google Workspace API. 
Fixes #823 and #839
=> Refactor/823 839/config logging/google integration

app/jobs/revoke_aws_sso_access.py, app/jobs/scheduled_tasks.py, app/tests/jobs/test_revoke_aws_sso_access.py, app/tests/jobs/test_scheduled_tasks.py
=> refactor: replace logging with structured logger

app/core/config.py, app/modules/dev/aws_dev.py, app/modules/dev/core.py, app/modules/dev/google.py, app/modules/dev/incident.py, app/modules/sre/sre.py
Refactor dev module with core config and logging
=> Refactor/config logging/dev module

app/core/config.py, app/modules/atip/atip.py, app/tests/modules/atip/test_atip.py
Update ATIP module to use core config and logging. Fixes #817 and #856
=> Refactor/817 856/config logging/atip module

app/modules/slack/webhooks.py, app/modules/slack/webhooks_create.py, app/modules/slack/webhooks_list.py, app/tests/modules/slack/test_slack_webhooks.py, app/tests/modules/slack/test_webhooks_create.py, app/tests/modules/slack/test_webhooks_list.py
=> refactor(Slack): replace logging with structured logger

app/modules/secret/secret.py, app/tests/modules/secret/test_secret.py
=> refactor(secret): use structured logger

app/core/config.py, app/integrations/google_workspace/google_drive.py, app/modules/role/role.py, app/tests/modules/role/test_role.py
=> Refactor/821 834/config logging/role module

app/core/config.py, app/main.py, app/modules/aws/aws.py, app/modules/aws/aws_access_requests.py, app/modules/aws/aws_account_health.py, app/modules/aws/groups.py, app/modules/aws/identity_center.py, app/modules/aws/lambdas.py, app/modules/aws/spending.py, app/modules/aws/users.py, app/tests/modules/aws/test_aws.py, app/tests/modules/aws/test_aws_access_requests.py, app/tests/modules/aws/test_aws_account_health.py, app/tests/modules/aws/test_aws_groups.py, app/tests/modules/aws/test_aws_lambdas.py, app/tests/modules/aws/test_aws_users.py, app/tests/modules/aws/test_spending.py, app/tests/modules/aws/test_sync_identity_center.py
=> Refactor/816 830/config logging/aws module

.github/workflows/build_and_deploy.yml
Reducing scope of workflow to avoid running unless the app actually got updated.
=> chore: update build and deploy workflow to ignore specific paths

app/modules/sre/sre.py, app/tests/modules/sre/test_sre.py
=> Refactor(sre): migrate to core config and logging

app/core/config.py, app/server/event_handlers/aws.py, app/server/server.py, app/server/utils.py, app/tests/modules/incident/test_incident.py, app/tests/server/event_handlers/test_aws_handler.py, app/tests/server/test_server.py, app/tests/test_main.py, app/utils/filters.py
=> Refactor/832 866/config logging/server

app/api/dependencies/rate_limits.py, app/api/router.py, app/api/routes/system.py, app/main.py, app/server/server.py, app/tests/api/dependencies/test_rate_limits.py, app/tests/api/routes/test_system.py, app/tests/server/test_server.py
=> Refactor/796 797/transition structure

terraform/variables.tf, terraform/waf.tf
Add missing endpoints to the waf rules
Use dynamic endpoints generation
=> feat: add authorized endpoints with constraints for WAF rules

.github/workflows/build_and_deploy.yml
=> fix: correct paths-ignore entry for terraform directory

app/core/security.py
temporarely log the jwt functions details to debug prod
=> tmp: add logging to debug endpoint call

app/core/config.py, app/core/security.py
Adding more debugging logs to fix the secure endpoint
=> tmp: add more logs to debug the secure endpoint

terraform/sns.tf, terraform/vpc.tf
Encrypting SNS topic with a KMS key to satisfy 30 day guardrail controls.
=> Encrypting SNS topic for alarms due to guardrails requirements

catalog-info.yaml
Enable Backstage Code Coverage plugin
=> feat: enable code coverage plugin
